### ISSUE TITLE
FE: sign up/log in

### ISSUE THREAD

**Issue by CodeJellee** [DrivenIIDevelop/DevCverse#8]

**Comment by CodeJellee** [comment]
@YuChienChou made the component

Need assist with creating the page for the component to render, help from Severian?

**Comment by CodeJellee** [comment]
Refer to user flow 1 on figma: https://www.figma.com/file/gMi1Qh5P6sWR3aoVD0CTze/UX-Design?type=design&node-id=908%3A6547&mode=design&t=umxihLwxOpQZAEOM-1

![Screenshot 2024-04-22 at 10 28 18 PM](https://github.com/DrivenIIDevelop/DevCverse/assets/108435185/e628e659-4196-4aa4-9e27-bdb30497d500)

**Comment by DylanD1192** [comment]
I'l be helping out with this task. To confirm, the page needs to be created and the components need top be added?

**Comment by CodeJellee** [comment]
Just some quick updates/clarifications from the deisgners:

When the top right profile icon is clicked, a drop down should come up with 'Sign Up' or 'Create Account'

Log in will have a model pop up from the right side as per the photo
![Screenshot 2024-04-23 at 2 33 22 PM](https://github.com/DrivenIIDevelop/DevCverse/assets/108435185/70445b47-681f-40c7-afb4-2e8f3d4b3406)

Error handling below:
![Screenshot 2024-04-23 at 2 34 58 PM](https://github.com/DrivenIIDevelop/DevCverse/assets/108435185/ddb86361-0d23-4b11-96b1-44a49f894c62)



If you were to crate a new account, it should open up to a new page:
![Screenshot 2024-04-23 at 2 33 48 PM](https://github.com/DrivenIIDevelop/DevCverse/assets/108435185/03f5433c-72d2-4d11-afa2-1097c77bb1c3)

**Comment by DRD161** [comment]
This has been completed, closing this issue.
